### ISSUE TITLE
Broken links in readme

### ISSUE THREAD

**Issue by nelsonic** [twitter/plumage.js#7]
Hi @mclin
This project sounds promising!
But when I try to find out more, getting dead links...

Tried clicking on the links in the README ... got 404 for all of them.

![plumage-404-also](https://cloud.githubusercontent.com/assets/194400/6765972/57ef0160-cfec-11e4-98e9-e0b7b5636936.png)

Same story on the http://twitter.github.io/plumage.js/ page...
try clicking on the **form fields** link in the **Batteries Included** section:

![plumage-404](https://cloud.githubusercontent.com/assets/194400/6765968/334aaec2-cfec-11e4-8d29-ed140ebc129a.png)

I would submit a PR if I could find them in the project...

**Comment by mclin** [comment]
Hey thanks for the interest. I fixed the links here.

https://github.com/twitter/plumage.js/commit/9463bae66f7b048161f0ceb32d889c7178eb593c

will do a gh-pages deploy shortly.
